//###硬度2的方块
//#半砖
"polished_blackstone_double_slab",
"polished_blackstone_slab",
//#半砖（包含许多不符合条件的方块）
"double_stone_slab",
"stone_slab",
"double_stone_slab2",
"stone_slab2",
"double_stone_slab3",
"stone_slab3",
"double_stone_slab4",
"stone_slab4",
//#墙
"polished_blackstone_wall",
//#墙（包含许多不符合条件的方块）
"cobblestone_wall",
//#楼梯
"stone_stairs", //圆石
"mossy_cobblestone_stairs",
"brick_stairs",
"nether_brick_stairs",
"red_nether_brick_stairs",
"polished_blackstone_stairs",
//#栅栏
"nether_brick_fence",
//#方块
"cobblestone",
"mossy_cobblestone",
"bone_block",
"brick_block",
"polished_blackstone",
"chiseled_polished_blackstone",
"nether_brick",
"red_nether_brick",
"cracked_nether_bricks",
"chiseled_nether_bricks",
"smooth_stone",